import type { Metadata } from "next";
import "./globals.scss";

// import { ServerStyleSheet } from "styled-components";
// import GlobalStyle from "../../styles/globalStyles";
// import { ThemeProvider } from "styled-components";
// import theme from "../../styles/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title?.toString()}</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
